title: ELIXIR-hCNV implementation study Report
logo: /assets/img/humman_variations_community_icon.png
description: This website shows our progress with the ongoing hCNV implementation study.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
